server:
  port: 8082
spring:
  application:
    name: seata-provider-order
  datasource:
    url: jdbc:mysql://139.155.68.87:3306/seata_order?useUnicode=true&characterset=utf8
    username: root
    password: 123456
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.68.87:8848
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      server-addr: 139.155.68.87:8848
      dataId: seata.properties
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 139.155.68.87:8848
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
