server:
  port: 80
spring:
  application:
    name: gateway-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.68.87:8848
    gateway:
      routes:
        - id: user
#          uri: http://localhost:8080  #  这里是uri不是url；未使用负载均衡，直接用ip+port访问
          uri: lb://gateway-user
          predicates:  # 断言
#            - Path=/user/**
#            - Before=2023-08-28T15:04+08:00[Asia/Shanghai]
#            - Cookie=serviceName,user
#            - Header=sName,user
#            - Method=GET
            - Host=127.0.0.1
          filters:
#            - StripPrefix=1
            - AddRequestHeader=name,ryans
            - RemoveJsonAttributesResponseBody=msg
            - name: My
              args:
                name: ryans
        - id: product
          uri: lb://gateway-product
          predicates:  # 断言

          #            - After=2023-08-28T15:04+08:00[Asia/Shanghai]
          #            - Cookie=serviceName,product
#            - Path=/product/**
#            - Header=sName,product
#            - Method=POST
            - Host=localhost
#          filters:
#            - StripPrefix=1
    sentinel:
      transport:
        dashboard: 127.0.0.1:8890
      # 配置限流后的响应内容
      scg:
        fallback:
          # 两种模式，一种是response返回文字提示，一种是redirect，重定向跳转，需要同时配置red
          mode: response
          # 响应状态码
          response-status: 426
          # 响应体
          response-body: '{"code": 503, "msg": "限流了，稍后重试！"}'
