server:
  port: 8080
spring:
  application:
    name: rocketmq-provider
  cloud:
    stream:
      rocketmq:
        binder:
          name-server: 139.155.68.87:9876
        bindings:  # 定义
          producer-out-0:
            producer:
              group: output_1
      bindings:  # 使用，与定义的producer对应
        producer-out-0:
          destination: orderly
