server:
  port: 80
spring:
  application:
    name: seata-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.68.87:8848
seata:
  enabled: true
  application-id: ${spring.application.name}
  tx-service-group: ${spring.application.name}-tx-group
  config:
    type: nacos
    nacos:
      server-addr: 139.155.68.87:8848
      data-id: seata.properties
      group: SEATA_GROUP
  registry:
    type: nacos
    nacos:
      application: seata-server
      group: SEATA_GROUP
      server-addr: 139.155.68.87:8848
