server:
  port: 8081
spring:
  application:
    name: rocket-consumer
  cloud:
    stream:
      function:
        definition: sqlConsumer;tagConsumer
      rocketmq:
        binder:
          name-server: 139.155.68.87:9876
        bindings:
          sqlConsumer-in-0:
            consumer:
              subscription: sql:(color in ('red','green') and price>3)  # color为红色或绿色,并且价格大于3
          tagConsumer-in-0:
            consumer:
              subscription: tag1||tag2
          consumer-in-0:
            consumer:
              messageModel: BROADCASTING  # 广播消息
      bindings:
        sqlConsumer-in-0:
          destination: sql_topic  # 主题
          group: sql-group
        tagConsumer-in-0:
          destination: sql_topic
          group: tag-group
