server:
  port: 80
spring:
  application:
    name: consumer
  cloud:
    nacos:
      discovery:
        server-addr: 139.155.68.87:8848
    gateway:
      routes:
        - id: user
          url: http://localhost:8080/user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=1
