spring:
  application:
    name: consumer-sentinel
  cloud:
    sentinel:
      web-context-unify: false
      transport:
        dashboard: 127.0.0.1:8890
      eager: true  # 动态刷新
      datasource:
        flow-ds:
          nacos:
            server-addr: 139.155.68.87:8848
            data-id: ${spring.application.name}-flow-rule
            data-type: json
            group-id: SENTINEL_GRUOP
            rule-type: flow

